wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717616447.0
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
